### ISSUE TITLE
1 - Draft down all the necessary details a user needs to give to create an account

### ISSUE THREAD

**Issue by yasgreen93** [Joypoints/Planning#1]

**Comment by yasgreen93** [comment]
![img_4812](https://user-images.githubusercontent.com/15678246/38453809-724c641a-3a53-11e8-91fb-d9fddd1fb4bd.jpg)

**Comment by yasgreen93** [comment]
Details needed:
```
USERID
FIRST NAME
LAST NAME
BIO
JOYCOINS
INTERESTS
METRICS
PHOTO
CLAN ID
EVENT IDS
```
Questions for @OlliePorter and @Ben-D-JP :
- Interests: Do we want to give the ability to add more than 3 interests?
- Metrics: What about when people reach their 150 person limit for their clan?
  - Realistically are people going to be adding people every week?
  - How many people do you add on Facebook per week for example?

**Comment by OlliePorter** [comment]
@yasgreen93 

For interests I think we should cap it to x3 interests & x3 non interests for now? At least in MVP, then we can add the options to add more down the line. 

When someone reaches their 150 limit I think we should send them a message saying you've filled your Clan. I'm sure the times people would add others to their clans would vary, either initial adding at sign up, or week by week.

**Comment by yasgreen93** [comment]
@OlliePorter Ok that's great. I will wait for @Ben-D-JP 's thumbs up and then I shall mark as done.

**Comment by yasgreen93** [comment]
Team agreements:
- A maximum of 3 is too little
- Should be a minimum of 3 with no maximum.
- Design like pinterest where there is a readymade list and you just click on the ones you want to add.
- "Non-interests" not needed for MVP but added in V2.0 - collect data in the background from feedback forms.

**Comment by yasgreen93** [comment]
There are a few more attributes needed for example, the ranking for this ticket to progress (will be done by @OlliePorter and @Ben-D-JP ). I will put on hold until we have this information. More information in this document here: https://docs.google.com/document/d/1eOvDmejE3MBtla_Pw7-TBNbI6zTL16bTnMQrDwlq3yQ/edit

**Comment by OlliePorter** [comment]
Working on finalising the first part of our Onboarding flow through InVision. Currently thinking about streamlining our customer sign up details as follows:

PHOTO (GRAVATER OR FACEBOOK PROFILE PIC)
FULL NAME (FIRST + LAST NAME)
EMAIL
PASSWORD

Second step would be: 
VALUES DISCLAIMER
INTERESTS (LIKE PINTEREST)
CLANS

After they've signed up to the app we could then prompt them to:
ADD A BIO
ADD PHONE NUMBER 
ADD PHOTO IF NOT DONE

**Comment by yasgreen93** [comment]
Removing `on hold` label - team to decided ranks and thresholds. More details here: https://docs.google.com/document/d/1eOvDmejE3MBtla_Pw7-TBNbI6zTL16bTnMQrDwlq3yQ/edit
Stored in DB will be number of Joycoins and then the rank from that (the logic for the thresholds however will not be worked out in the models).

**Comment by OlliePorter** [comment]
In progress. Currently writing the rank specifications and working out the answers to these questions:

- What are Joypoints ranks? (names, points threshold for each, master rank)
- How many Joycoins will you receive at Drop Out? (with UI for Drop Out)
- What does the UI for profile page look like with integration of rank journey & achievements
- What are Joypoints achievements (what’s unlockable and how i.e. challenges/medals)

**Comment by Ben-D-JP** [comment]
In progress still?

**Comment by OlliePorter** [comment]
Joy Ranks updated:

Rank 1 - Joybie -> 0 coins
Rank 2 - Trendsetter -> 50 coins (10 Drop Outs)
Rank 3 - Smooth Sailor -> 100 coins (20 Drop Outs)
Rank 4 - The Enlightened One -> 200 coins (40 Drop Outs)
Rank 5 - Pro Joy -> 300 coins (60 Drop Outs)
Rank 6 - -> 400 coins (80 Drop Outs)
Rank 7 - -> 500 coins (100 Drop Outs)
Rank 8 - Top Joyager -> 700 coins (140 Drop Outs)
Rank 9 - (VIJ) Very Important Joyager -> 900 coins (180 Drop Outs)
Rank 10 - Master of Joy -> 1000 coins (200 Drop Outs) + Induction to rewards program

Joyagers will receive *5 Joy Coins* at every Drop Out. Master of Joy status is reached at 1000 coins (which is 200 Get-Togethers).

Review from @yasgreen93 and @Ben-D-JP  needed.

**Comment by yasgreen93** [comment]
I think this would be good to discuss in the kickoff.

**Comment by yasgreen93** [comment]
Team agreement:
- Happy with thresholds, designed to be unachievable until we launch the reward card scheme with V2.0.
- Happy with achievements.

Need the ship sign from @Ben-D-JP and @OlliePorter.

**Comment by Ben-D-JP** [comment]
ship

**Comment by yasgreen93** [comment]
Both giving the ship so marking as done.
