### ISSUE TITLE
2 - Draft down all of the details needed in a clan

### ISSUE THREAD

**Issue by yasgreen93** [Joypoints/Planning#2]

**Comment by yasgreen93** [comment]
Discussion needed for this point: https://docs.google.com/document/d/1YIdFzC3XPwZM5jAR4Ai95QZ7T4YH26ZfwIyjRqN--Lk/edit?disco=AAAABgEIqtQ

**Comment by yasgreen93** [comment]
- Team have agreed to leave in the tiers but on first MVP, instead of having `recent`, `overdue` and `all` we just have the `all` section. On-boarding has to be streamlined and effective.
- V2.0 - we can bring in the `recent`, `overdue` sections also.

**Comment by yasgreen93** [comment]
@OlliePorter @Ben-D-JP what did we decide on tiers??

**Comment by yasgreen93** [comment]
Yasmin is a silly billy because Yasmin wrote the answer above. 😂

**Comment by yasgreen93** [comment]
![clan-logic.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570241db0e4a9713004018ae/125516c66e82c728ace21e0d46eb989b2dcf8fa688e0bc01e81fe086264c22703d46f9692584e070bb1329500d5b18ad47595f44fefc8d2ba4e03526984019af80330b2b9b645bf9fa9015ad00b22a8a4a87b3b48a4bc3e03423e38d9d02.jpg)

```
- ID - clan ID
- USERID - ID of the user who owns the clan
- TIER-ONE -  [{USERID: <string>, LAST-SEEN: <date/time>}]
- TIER-TWO -  [{USERID: <string>, LAST-SEEN: <date/time>}]
- TIER-THREE -  [{USERID: <string>, LAST-SEEN: <date/time>}]
```
> Split into 3 tiers and each tier is split into 3 categories:
>- Tier 1 - “Close friends” - notification frequency - 1-2 weeks
>    - Recent - people you’ve seen within the past week (7 days)
>    - Overdue - people that you have not seen in over 2 weeks (14 days)
>    - All - all people in that tier.
>- Tier 2 - “More friends” - notification frequency - 2-4 weeks
>    - Recent - people you’ve seen within the past 2 weeks (14 days)
>    - Overdue - people that you have not seen in over 4 weeks (28 days)
>    - All - all people in that tier.
>- Tier 3 - “Acquaintances” - notification frequency - 4+ weeks
>    - Recent - people you’ve seen within the past 4 weeks (28 days)
>    - Overdue - people that you have not seen in over 8 weeks (56 days)
>    - All - all people in that tier.

- The logic above ^ will go in the controller. The only reference to when a user last saw someone that is saved into the DB will be a date-time attribute. The categorisation will go in the controller.

- If a user has not seen someone in their clan before, `LAST-SEEN` will be `null`.  The controller logic will then sort that person into the `ALL` category.
- If a user has a `LAST-SEEN` for a user as a `date-time`attribute then they will be sorted into `RECENT` or `OVERDUE` depending on that tier's category logic.

**Comment by OlliePorter** [comment]
Ship from me :)

**Comment by Ben-D-JP** [comment]
Ship :)
