### ISSUE TITLE
3 - Draft down all the necessary details a user needs to give to create a get together

### ISSUE THREAD

**Issue by yasgreen93** [Joypoints/Planning#3]

**Comment by yasgreen93** [comment]
![img_4815](https://user-images.githubusercontent.com/15678246/38456229-350d3b3e-3a7a-11e8-8d52-c91b5eb8be49.jpg)

```
EVENT ID
USER ID
TITLE
LOCATION
DATE/TIME
DESCRIPTION
CATEGORY
STATUS
ATTENDEE IDs
```

- Validate form to check that they haven't filled in their name anywhere
- `STATUS` options:
  - `ACTIVE` - Event created and waiting to be started
  - `CANCELLED` - Event cancelled
  - `NO ATTENDEES` - No attendees for the user's event
  - `ATTENDEE DECLINED` - One or more attendees declined the event
  - `WAITING FOR DROP INS` - One or more persons have dropped in, waiting for everyone to drop in
  - `IN PROGRESS` - Everyone has dropped in and the event is in progress
  - `COMPLETED` - Event has been completed
  - `LATE ATTENDEE` - One or more attendees are running late

The event can have more than one status (array of statuses).

- Location uses Google Maps API with auto suggestions etc.
- Date/Time uses native date/time picker.

**Comment by OlliePorter** [comment]
:shipit: from me. Looks great!

**Comment by Ben-D-JP** [comment]
If Ol's happy I'm happy!

**Comment by yasgreen93** [comment]
All team members give 👍. Closing #3

**Comment by yasgreen93** [comment]
![user-event-relationships](https://user-images.githubusercontent.com/15678246/39070078-de531916-44d9-11e8-86eb-db433be8d966.jpg)
