### ISSUE TITLE
4 - Draft down all the necessary routes and endpoints for the API gateway

### ISSUE THREAD

**Issue by yasgreen93** [Joypoints/Planning#4]

**Comment by yasgreen93** [comment]
User endpoint difficulties: https://forums.aws.amazon.com/thread.jspa?threadID=232023

**Comment by yasgreen93** [comment]
@OlliePorter and @Ben-D-JP to check over to see if I have forgotten anything or have any questions.

**Comment by OlliePorter** [comment]
🚢from me. I think you covered the core points to each. I'm sure we'll expand further features as we build out the platform. The only thing I can think of is searching user.

**Comment by Ben-D-JP** [comment]
🚢 from me then too :)

**Comment by yasgreen93** [comment]
Both ship so marking as done :)
