### ISSUE TITLE
7 - Draft down all of the database tables needed and the relationships between them

### ISSUE THREAD

**Issue by yasgreen93** [Joypoints/Planning#7]

**Comment by yasgreen93** [comment]
### Tables needed:
- `USER` - details of the exact attributes are in #1 
- `EVENT` - details of the exact attributes are in #3 
- `CLAN` - details of the exact attributes are in #2 

![user-clan-relationships](https://user-images.githubusercontent.com/15678246/39087873-96079be8-459f-11e8-9662-e6b72099e589.jpg)
![user-event-relationships](https://user-images.githubusercontent.com/15678246/39087874-961c1794-459f-11e8-8575-ae26f4ddbaf5.jpg)

_N.B. you will notice a lot of references to "events" rather than "get-togethers" from a tech point of view this is on purpose because for creating endpoints and database tables it is a much more concise word._

**Comment by yasgreen93** [comment]
@OlliePorter and @Ben-D-JP to check if I have missed anything.

**Comment by OlliePorter** [comment]
Looks good to me. Before I ship my end, question about the 'One get-together can have many attendees.' The events will be done on a 1 : 1 basis (for now), so the question we need to answer is what happens on both ends, from the owner of the get-together to the observer/attendee of the get together when they accept or decline the event. What do said actions do and look like.

**Comment by Ben-D-JP** [comment]
And do the new data laws affect this?

**Comment by yasgreen93** [comment]
About @OlliePorter 's comment: 
- From an engineering perspective I think this is fine because the event will always have more than one attendee: the owner and the invitee. This also leaves it open in the future for us to expand get-togethers to more than 1 : 1.
- With regards to this part:
```
...so the question we need to answer is what happens on both ends, from the owner of the get-together to the observer/attendee of the get together when they accept or decline the event. What do said actions do and look like.
```
  This is a great point, I believe this is for another ticket as part of the design process. We can discuss this in the kickoff on Monday? @Ben-D-JP thoughts?

**Comment by OlliePorter** [comment]
Agreed on both. Happy to expand this to separate design ticket for us to talk through on Monday.

**Comment by Ben-D-JP** [comment]
Ship

**Comment by yasgreen93** [comment]
Both giving the ship, marking as done
