### ISSUE TITLE
8 - Draft down what is needed to be stored in S3

### ISSUE THREAD

**Issue by yasgreen93** [Joypoints/Planning#8]

**Comment by yasgreen93** [comment]
- User profile picture
- Event photos (see screenshots below):
![pics.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570241db0e4a9713004018ae/125516c66e82c728ace21e0d46f89d9930c0cfeb9ffbb049a15ee4d6730472722a5ca77a22d4e17cb9132d505f5f4ca945585d12f5af9b37b4f46d2ede0356b49b381d66cc2f13acb2831abd05be21884a83b1b88344d2a5.jpg)

**Comment by Ben-D-JP** [comment]
🚢

**Comment by Ben-D-JP** [comment]
Does the toolbar need to be present on the bottom of the lefthand screenshot?

**Comment by yasgreen93** [comment]
@Ben-D-JP that's a great question for @OlliePorter something else to discuss in the kickoff. I don't think this affects the status of this ticket so marking as done.

**Comment by yasgreen93** [comment]
Outcome from kickoff:
- No it doesn't need to be there because it would ruined the user get-together finding process.
