### ISSUE TITLE
9 - Figure out how to work out when it is a user's first visit to show the first intro screen

### ISSUE THREAD

**Issue by yasgreen93** [Joypoints/Planning#9]
What about a tutorial option in the settings?

**Comment by Ben-D-JP** [comment]
First time they open the app?

**Comment by yasgreen93** [comment]
Potential package for implementation: https://github.com/FuYaoDe/react-native-app-intro

**Comment by yasgreen93** [comment]
@OlliePorter and @Ben-D-JP - this ticket is for tech thoughts only, I think I have all I need from a tech point of view so shall consider this ticket done and will close. 👍
